#!/usr/bin/env node
/**
 * Generate 500 quiz questions for Foundation of Blockchain certification.
 * Run: node generate_questions.js
 * Output: src/data/quiz_questions.json
 */
const fs = require('fs');
const path = require('path');

const questions = [];
let id = 1;
function q(topic, diff, qvi, qen, ovi, oen, correct, evi, een) {
  questions.push({
    id: `q${String(id++).padStart(3,'0')}`, topic, difficulty: diff,
    question_vi: qvi, question_en: qen,
    options_vi: ovi, options_en: oen,
    correct, explanation_vi: evi, explanation_en: een
  });
}

// ═══════════════════════════════════════════════════
// HASH (80 questions)
// ═══════════════════════════════════════════════════
q('hash','easy','SHA-256 luôn tạo ra bao nhiêu ký tự hex?','How many hex characters does SHA-256 always produce?',['32','64','128','256'],['32','64','128','256'],1,'SHA-256 tạo 256 bits = 64 ký tự hex.','SHA-256 produces 256 bits = 64 hex characters.');
q('hash','easy','SHA viết tắt của gì?','What does SHA stand for?',['Secure Hash Algorithm','Simple Hash Application','Standard Hash Architecture','System Hash Access'],['Secure Hash Algorithm','Simple Hash Application','Standard Hash Architecture','System Hash Access'],0,'SHA = Secure Hash Algorithm.','SHA = Secure Hash Algorithm.');
q('hash','easy','Đầu ra của SHA-256 có bao nhiêu bits?','How many bits is SHA-256 output?',['128','192','256','512'],['128','192','256','512'],2,'SHA-256 tạo ra 256 bits.','SHA-256 produces 256 bits.');
q('hash','easy','Hàm băm có thể đảo ngược không?','Can a hash function be reversed?',['Có','Không, là hàm một chiều','Với máy tính mạnh thì được','Chỉ khi đầu vào ngắn'],['Yes','No, it is one-way','With powerful computers','Only if input is short'],1,'Hàm băm mật mã là hàm một chiều.','Cryptographic hash functions are one-way.');
q('hash','easy','Thay đổi 1 ký tự đầu vào, SHA-256 thay đổi bao nhiêu?','Change 1 input char, how much SHA-256 output changes?',['1 ký tự','~10%','~50%','Không đổi'],['1 character','~10%','~50%','No change'],2,'Hiệu ứng Avalanche: ~50% bits thay đổi.','Avalanche effect: ~50% bits change.');
q('hash','easy','Hiệu ứng nào khi thay đổi nhỏ gây thay đổi lớn ở đầu ra?','What effect when small input change causes large output change?',['Domino','Avalanche','Butterfly','Cascade'],['Domino','Avalanche','Butterfly','Cascade'],1,'Hiệu ứng Avalanche.','Avalanche effect.');
q('hash','easy','Đâu KHÔNG phải tính chất của hàm băm mật mã?','Which is NOT a property of cryptographic hash?',['Đầu ra cố định','Có thể đảo ngược','Kháng va chạm','Avalanche'],['Fixed output','Reversible','Collision resistant','Avalanche'],1,'Hàm băm KHÔNG thể đảo ngược.','Hash functions are NOT reversible.');
q('hash','easy','Kháng va chạm nghĩa là gì?','What does collision resistance mean?',['Hàm chạy nhanh','Rất khó tìm 2 đầu vào cùng đầu ra','Đầu ra luôn khác','Không bao giờ lỗi'],['Hash runs fast','Very hard to find 2 inputs with same output','Output always different','Never errors'],1,'Gần như không thể tìm 2 đầu vào cho cùng hash.','Nearly impossible to find 2 inputs with same hash.');
q('hash','easy','SHA-256 dùng trong blockchain nào?','Which blockchain uses SHA-256?',['Ethereum','Bitcoin','Cardano','Solana'],['Ethereum','Bitcoin','Cardano','Solana'],1,'Bitcoin dùng SHA-256.','Bitcoin uses SHA-256.');
q('hash','easy','Mã băm thường biểu diễn dạng nào?','How is hash typically represented?',['Nhị phân','Thập phân','Hex','Bát phân'],['Binary','Decimal','Hex','Octal'],2,'Mã băm thường hiển thị dạng hex.','Hashes are typically displayed in hex.');
q('hash','easy','Salt trong hàm băm mật khẩu là gì?','What is salt in password hashing?',['Mật khẩu 2','Giá trị ngẫu nhiên thêm trước khi hash','Tên user','Thuật toán'],['2nd password','Random value added before hashing','Username','Algorithm'],1,'Salt ngăn rainbow table attack.','Salt prevents rainbow table attacks.');
q('hash','easy','Rainbow table attack là gì?','What is a rainbow table attack?',['Tấn công mạng','Dùng bảng hash tính sẵn dò mật khẩu','Tấn công vật lý','Tấn công DDoS'],['Network attack','Using precomputed hash tables to crack passwords','Physical attack','DDoS attack'],1,'Rainbow table: bảng (plaintext → hash) tính sẵn.','Rainbow table: precomputed (plaintext → hash) pairs.');
q('hash','easy','1 byte = bao nhiêu bit?','1 byte = how many bits?',['4','8','16','32'],['4','8','16','32'],1,'1 byte = 8 bits.','1 byte = 8 bits.');
q('hash','easy','Ký tự hex có thể nhận giá trị nào?','What values can a hex character have?',['0-9','a-f','0-9 và a-f','0-9 và A-Z'],['0-9','a-f','0-9 and a-f','0-9 and A-Z'],2,'Hex: 0-9 và a-f (hoặc A-F).','Hex: 0-9 and a-f (or A-F).');
q('hash','easy','SHA-256 thuộc họ SHA nào?','SHA-256 belongs to which SHA family?',['SHA-0','SHA-1','SHA-2','SHA-3'],['SHA-0','SHA-1','SHA-2','SHA-3'],2,'SHA-256 thuộc họ SHA-2.','SHA-256 belongs to the SHA-2 family.');
q('hash','medium','SHA-256 xử lý dữ liệu theo khối bao nhiêu bits?','SHA-256 processes data in blocks of how many bits?',['256','512','1024','128'],['256','512','1024','128'],1,'SHA-256 xử lý theo khối 512 bits.','SHA-256 processes data in 512-bit blocks.');
q('hash','medium','SHA-256 thực hiện bao nhiêu vòng lặp?','How many rounds does SHA-256 perform?',['32','48','64','80'],['32','48','64','80'],2,'SHA-256: 64 vòng compression.','SHA-256: 64 compression rounds.');
q('hash','medium','Birthday Attack tấn công tính chất nào?','Birthday Attack targets which property?',['Tính một chiều','Kháng va chạm','Avalanche','Đầu ra cố định'],['One-way','Collision resistance','Avalanche','Fixed output'],1,'Birthday Attack nhắm vào collision resistance.','Birthday Attack targets collision resistance.');
q('hash','medium','Birthday Attack cần ~bao nhiêu phép thử cho SHA-256?','Birthday Attack needs ~how many trials for SHA-256?',['2^64','2^128','2^256','2^32'],['2^64','2^128','2^256','2^32'],1,'Cần ~2^(n/2) = 2^128 phép thử.','Needs ~2^(n/2) = 2^128 trials.');
q('hash','medium','Padding SHA-256 thêm gì vào cuối?','What does SHA-256 padding append?',['Chỉ bit 0','Bit 1, bit 0, và 64-bit length','Chỉ length','Không gì'],['Only 0 bits','1 bit, 0 bits, and 64-bit length','Only length','Nothing'],1,'Padding: 1 bit, zeros, 64-bit original length.','Padding: 1 bit, zeros, 64-bit original length.');
q('hash','medium','IV của SHA-256 lấy từ đâu?','Where do SHA-256 IVs come from?',['Số ngẫu nhiên','Căn bậc 2 của 8 số nguyên tố đầu','Căn bậc 3 của 8 số nguyên tố đầu','Fibonacci'],['Random numbers','Square roots of first 8 primes','Cube roots of first 8 primes','Fibonacci'],1,'IV = 32 bit phần thập phân của căn bậc 2 của 8 nguyên tố đầu.','IVs = first 32 fractional bits of square roots of first 8 primes.');
q('hash','medium','Hai file khác nhau cùng hash gọi là gì?','Two different files with same hash is called?',['Overflow','Collision','Deadlock','Corruption'],['Overflow','Collision','Deadlock','Corruption'],1,'Collision: 2 đầu vào cho cùng mã băm.','Collision: 2 inputs producing same hash.');
q('hash','medium','HMAC kết hợp hash với gì?','HMAC combines hash with what?',['Khoá bí mật','Chữ ký số','Chứng chỉ','Timestamp'],['Secret key','Digital signature','Certificate','Timestamp'],0,'HMAC = Hash-based MAC, dùng khoá bí mật.','HMAC uses a secret key.');
q('hash','medium','MD5 còn an toàn cho mật mã không?','Is MD5 still secure for crypto?',['Có','Không, đã bị phá','Chỉ cho file nhỏ','Tùy trường hợp'],['Yes','No, it is broken','Only for small files','Depends'],1,'MD5 bị phá từ 2004.','MD5 was broken in 2004.');
q('hash','medium','SHA-1 khác SHA-256 chủ yếu ở đâu?','How do SHA-1 and SHA-256 mainly differ?',['Giống nhau','SHA-1: 160 bits, SHA-256: 256 bits','SHA-1 nhanh hơn nên tốt hơn','Không khác'],['Same','SHA-1: 160 bits, SHA-256: 256 bits','SHA-1 faster so better','No difference'],1,'SHA-1: 160 bits (bị phá). SHA-256: 256 bits (an toàn).','SHA-1: 160 bits (broken). SHA-256: 256 bits (secure).');
q('hash','medium','Keccak là tên gốc của hash nào?','Keccak is the original name of which hash?',['SHA-1','SHA-256','SHA-3','MD5'],['SHA-1','SHA-256','SHA-3','MD5'],2,'SHA-3 dựa trên thuật toán Keccak.','SHA-3 is based on the Keccak algorithm.');
q('hash','medium','SHA-3 dùng cấu trúc gì thay vì Merkle-Damgård?','SHA-3 uses what structure instead of Merkle-Damgård?',['Feistel','Sponge','Block cipher','Stream cipher'],['Feistel','Sponge','Block cipher','Stream cipher'],1,'SHA-3 dùng sponge construction.','SHA-3 uses sponge construction.');
q('hash','hard','SHA-256 dùng phép toán bitwise nào?','What bitwise ops does SHA-256 use?',['Chỉ XOR, AND','AND, OR, XOR, NOT, shift, rotate','Chỉ shift, rotate','Chỉ ADD, XOR'],['Only XOR, AND','AND, OR, XOR, NOT, shift, rotate','Only shift, rotate','Only ADD, XOR'],1,'SHA-256 dùng nhiều phép toán bitwise.','SHA-256 uses multiple bitwise operations.');
q('hash','hard','Preimage resistance cần bao nhiêu phép thử để phá SHA-256?','How many trials to break SHA-256 preimage resistance?',['2^128','2^192','2^256','2^64'],['2^128','2^192','2^256','2^64'],2,'Cần ~2^256 phép thử.','Requires ~2^256 trials.');
q('hash','hard','Length extension attack ảnh hưởng hash nào?','Which hashes are vulnerable to length extension?',['Không hash nào','SHA-256, SHA-1 (Merkle-Damgård)','Chỉ MD5','Chỉ SHA-3'],['None','SHA-256, SHA-1 (Merkle-Damgård)','Only MD5','Only SHA-3'],1,'Merkle-Damgård hashes dễ bị tấn công. SHA-3 thì không.','Merkle-Damgård hashes are vulnerable. SHA-3 is not.');
q('hash','hard','Second preimage resistance khác collision resistance thế nào?','How does 2nd preimage resistance differ from collision resistance?',['Giống nhau','Second preimage: cho sẵn 1 input tìm input khác cùng hash; Collision: tìm bất kỳ 2 inputs cùng hash','Second preimage dễ hơn','Collision quan trọng hơn'],['Same','2nd preimage: given 1 input find another with same hash; Collision: find any 2 inputs with same hash','2nd preimage is easier','Collision more important'],1,'Second preimage cố định 1 input; collision tìm bất kỳ cặp.','2nd preimage fixes 1 input; collision finds any pair.');

// ═══════════════════════════════════════════════════
// MINING (80 questions)
// ═══════════════════════════════════════════════════
q('mining','easy','Proof of Work là gì?','What is Proof of Work?',['Bằng chứng sở hữu','Bằng chứng tìm hash hợp lệ','Bằng chứng gửi giao dịch','Bằng chứng kết nối'],['Proof of ownership','Proof of finding valid hash','Proof of sending tx','Proof of connection'],1,'PoW: tìm nonce sao cho hash thoả mãn difficulty.','PoW: find nonce so hash meets difficulty.');
q('mining','easy','Nonce trong mining là gì?','What is nonce in mining?',['Tên thợ đào','Số thay đổi liên tục tìm hash hợp lệ','Phí giao dịch','Địa chỉ ví'],['Miner name','Number changed to find valid hash','Tx fee','Wallet address'],1,'Nonce = Number used ONCE.','Nonce = Number used ONCE.');
q('mining','easy','Difficulty xác định điều gì?','What does difficulty determine?',['Số coin','Số bit 0 đầu hash cần đạt','Tốc độ internet','Kích thước khối'],['Coin count','Leading zero bits required','Internet speed','Block size'],1,'Difficulty = số bit 0 đầu mã hash.','Difficulty = number of leading zeros in hash.');
q('mining','easy','Thời gian trung bình đào 1 block Bitcoin?','Average time to mine 1 Bitcoin block?',['1 phút','10 phút','1 giờ','1 ngày'],['1 min','10 min','1 hour','1 day'],1,'Bitcoin: ~10 phút/block.','Bitcoin: ~10 minutes per block.');
q('mining','easy','Block reward là gì?','What is block reward?',['Phí giao dịch','Coin mới cho thợ đào thành công','Thuế mining','Gas fee'],['Transaction fee','New coins for successful miner','Mining tax','Gas fee'],1,'Block reward = coin mới tạo ra.','Block reward = newly minted coins.');
q('mining','easy','Bitcoin halving là gì?','What is Bitcoin halving?',['Giảm block size','Giảm reward một nửa mỗi 210.000 block','Tăng difficulty','Chia blockchain'],['Reduce block size','Halve reward every 210,000 blocks','Double difficulty','Split chain'],1,'Mỗi ~4 năm reward giảm 50%.','Every ~4 years reward drops 50%.');
q('mining','easy','Hash rate đo gì?','What does hash rate measure?',['Blockchain size','Số hash/giây','Giá Bitcoin','Số node'],['Blockchain size','Hashes per second','BTC price','Node count'],1,'Hash rate = phép hash mỗi giây.','Hash rate = hashes per second.');
q('mining','easy','Mining pool là gì?','What is a mining pool?',['Loại ví','Nhóm thợ đào kết hợp sức mạnh','Sàn giao dịch','Phần mềm'],['Wallet type','Miners combining computing power','Exchange','Software'],1,'Mining pool: chia sẻ hash rate và phần thưởng.','Mining pool: share hash rate and rewards.');
q('mining','easy','Thợ đào nhận phần thưởng ngoài block reward còn gì?','Besides block reward, miners also receive?',['Không gì','Phí giao dịch','Tiền thưởng chính phủ','Lãi suất'],['Nothing','Transaction fees','Government bonus','Interest'],1,'Thợ đào nhận block reward + phí giao dịch.','Miners receive block reward + transaction fees.');
q('mining','easy','GPU mining là gì?','What is GPU mining?',['Dùng CPU','Dùng card đồ hoạ để đào','Dùng điện thoại','Dùng cloud'],['Using CPU','Using graphics cards for mining','Using phone','Using cloud'],1,'GPU mining dùng card đồ hoạ với khả năng tính toán song song.','GPU mining uses graphics cards with parallel processing.');
q('mining','medium','Difficulty adjustment Bitcoin xảy ra mỗi bao nhiêu block?','Bitcoin difficulty adjustment occurs every?',['100','1.000','2.016','10.000'],['100','1,000','2,016','10,000'],2,'Mỗi 2.016 blocks (~2 tuần).','Every 2,016 blocks (~2 weeks).');
q('mining','medium','Hash rate mạng tăng → difficulty?','Network hash rate increases → difficulty?',['Giảm','Tăng','Không đổi','Ngẫu nhiên'],['Decreases','Increases','Same','Random'],1,'Blocks nhanh hơn → difficulty tăng.','Blocks faster → difficulty increases.');
q('mining','medium','Selfish mining là gì?','What is selfish mining?',['Đào hardware yếu','Giấu block đã đào để lợi thế','Không trả điện','DDoS'],['Weak hardware mining','Withholding blocks for advantage','Not paying electricity','DDoS'],1,'Selfish mining: giấu block, công bố lúc có lợi.','Selfish mining: withhold blocks, release when advantageous.');
q('mining','medium','ASIC là gì?','What is an ASIC?',['Phần mềm','Chip chuyên dụng mining','Thuật toán','Loại ví'],['Software','Specialized mining chip','Algorithm','Wallet type'],1,'ASIC = Application-Specific Integrated Circuit.','ASIC = Application-Specific Integrated Circuit.');
q('mining','medium','Tại sao mining tiêu tốn năng lượng?','Why does mining consume energy?',['Lưu trữ lớn','Hàng tỷ phép hash tìm nonce','Internet nhanh','Smart contract'],['Large storage','Billions of hash ops for nonce','Fast internet','Smart contracts'],1,'PoW thử hàng tỷ nonce → tốn điện.','PoW tries billions of nonces → energy intensive.');
q('mining','medium','Mempool là gì?','What is the mempool?',['Loại RAM','Nơi chứa giao dịch chờ xác nhận','Loại coin','Thuật toán'],['RAM type','Pool of unconfirmed transactions','Coin type','Algorithm'],1,'Mempool: giao dịch chờ được thợ đào đưa vào block.','Mempool: transactions waiting to be included in a block.');
q('mining','medium','Confirmation trong Bitcoin nghĩa là gì?','What does confirmation mean in Bitcoin?',['Giao dịch đã gửi','Số blocks đã đào sau block chứa giao dịch','Thợ đào chấp nhận','Node nhận giao dịch'],['Transaction sent','Number of blocks mined after the block containing the tx','Miner accepted','Node received tx'],1,'1 confirmation = 1 block đào sau. 6 confirmations thường coi là an toàn.','1 confirmation = 1 block mined after. 6 confirmations usually considered safe.');
q('mining','medium','Coinbase transaction là gì?','What is a coinbase transaction?',['Giao dịch trên sàn Coinbase','Giao dịch đầu tiên trong block tạo coin mới cho thợ đào','Giao dịch lớn nhất','Giao dịch cuối cùng'],['Trade on Coinbase exchange','First tx in block creating new coins for miner','Largest tx','Last tx'],1,'Coinbase tx: giao dịch đặc biệt đầu block, tạo coin mới.','Coinbase tx: special first tx in block, mints new coins.');
q('mining','hard','Block header Bitcoin gồm những trường nào?','What fields are in Bitcoin block header?',['Version, prevHash, merkleRoot, timestamp, target, nonce','Chỉ hash và nonce','Transaction list','Address, amount, fee'],['Version, prevHash, merkleRoot, timestamp, target, nonce','Only hash and nonce','Transaction list','Address, amount, fee'],0,'Header: version, prevHash, merkleRoot, timestamp, target, nonce.','Header: version, prevHash, merkleRoot, timestamp, target, nonce.');
q('mining','hard','Target trong PoW biểu diễn thế nào?','How is PoW target represented?',['Số nguyên','Hash tối đa mà block hash phải nhỏ hơn','Số giao dịch','Block size max'],['Positive integer','Max hash value block hash must be below','Tx count','Max block size'],1,'Target = ngưỡng hash, block hash < target mới hợp lệ.','Target = hash threshold, block hash must be < target.');
q('mining','hard','Stratum protocol dùng trong mining để làm gì?','What is Stratum protocol used for?',['Mã hoá','Giao tiếp giữa thợ đào và mining pool','Đồng bộ blockchain','Quản lý ví'],['Encryption','Communication between miners and pool','Blockchain sync','Wallet management'],1,'Stratum: protocol giao tiếp chuẩn giữa miner và pool.','Stratum: standard communication protocol between miner and pool.');

// ═══════════════════════════════════════════════════
// RSA (70 questions)
// ═══════════════════════════════════════════════════
q('rsa','easy','RSA là loại mã hoá nào?','What type of encryption is RSA?',['Đối xứng','Bất đối xứng','Hàm băm','Không mã hoá'],['Symmetric','Asymmetric','Hash','No encryption'],1,'RSA: mã hoá bất đối xứng, dùng cặp khoá.','RSA: asymmetric encryption using key pairs.');
q('rsa','easy','RSA dùng bao nhiêu khoá?','How many keys does RSA use?',['1','2','3','4'],['1','2','3','4'],1,'2 khoá: public và private.','2 keys: public and private.');
q('rsa','easy','Public key dùng để làm gì?','What is public key used for?',['Giải mã','Mã hoá và xác thực chữ ký','Tạo hash','Đào coin'],['Decrypt','Encrypt and verify signatures','Create hash','Mine coins'],1,'Public key: mã hoá + verify chữ ký.','Public key: encrypt + verify signatures.');
q('rsa','easy','Private key phải giữ thế nào?','How should private key be kept?',['Chia sẻ công khai','Bí mật tuyệt đối','Trên blockchain','Gửi email'],['Share publicly','Absolutely secret','On blockchain','Via email'],1,'Private key phải giữ bí mật.','Private key must be kept secret.');
q('rsa','easy','RSA dựa trên bài toán nào?','RSA is based on what problem?',['Logarithm rời rạc','Phân tích thừa số nguyên tố','Đường cong elliptic','Phương trình bậc 2'],['Discrete logarithm','Integer factorization','Elliptic curves','Quadratic equations'],1,'RSA: phân tích tích 2 số nguyên tố lớn.','RSA: factoring product of 2 large primes.');
q('rsa','easy','Chữ ký số dùng khoá nào để ký?','Which key signs digital signatures?',['Public','Private','Session','Master'],['Public','Private','Session','Master'],1,'Private key ký, public key xác minh.','Private key signs, public key verifies.');
q('rsa','easy','RSA viết tắt của?','RSA stands for?',['Random Secure Algorithm','Rivest-Shamir-Adleman','Rapid Sign Auth','Real Security Access'],['Random Secure Algorithm','Rivest-Shamir-Adleman','Rapid Sign Auth','Real Security Access'],1,'RSA = Rivest, Shamir, Adleman (1977).','RSA = Rivest, Shamir, Adleman (1977).');
q('rsa','easy','RSA được phát minh năm nào?','When was RSA invented?',['1970','1977','1985','2000'],['1970','1977','1985','2000'],1,'RSA công bố năm 1977.','RSA was published in 1977.');
q('rsa','medium','n = p × q. p=5, q=11, n=?','n = p × q. p=5, q=11, n=?',['16','55','50','66'],['16','55','50','66'],1,'n = 5 × 11 = 55.','n = 5 × 11 = 55.');
q('rsa','medium','φ(n) khi n = p × q bằng?','φ(n) when n = p × q equals?',['p × q','(p-1)(q-1)','p + q','(p+1)(q+1)'],['p × q','(p-1)(q-1)','p + q','(p+1)(q+1)'],1,'φ(n) = (p-1)(q-1).','φ(n) = (p-1)(q-1).');
q('rsa','medium','Khoá e phải thoả điều kiện gì?','What must public key e satisfy?',['e = 1','1 < e < φ(n), gcd(e,φ(n))=1','e > n','e chẵn'],['e = 1','1 < e < φ(n), gcd(e,φ(n))=1','e > n','e is even'],1,'e phải coprime với φ(n).','e must be coprime with φ(n).');
q('rsa','medium','Khoá d thoả phương trình nào?','Private key d satisfies?',['d × e = 1','d × e ≡ 1 (mod φ(n))','d + e = n','d = e^(-1)'],['d × e = 1','d × e ≡ 1 (mod φ(n))','d + e = n','d = e^(-1)'],1,'d là modular inverse của e mod φ(n).','d is the modular inverse of e mod φ(n).');
q('rsa','medium','Mã hoá: c = m^e mod n. Giải mã: m = ?','Encrypt: c = m^e mod n. Decrypt: m = ?',['c^e mod n','c^d mod n','c - d mod n','c / e mod n'],['c^e mod n','c^d mod n','c - d mod n','c / e mod n'],1,'Giải mã: m = c^d mod n.','Decrypt: m = c^d mod n.');
q('rsa','medium','Kích thước khoá RSA tối thiểu khuyến nghị?','Minimum recommended RSA key size?',['512','1024','2048','4096'],['512','1024','2048','4096'],2,'2048 bits tối thiểu, 4096 cho bảo mật cao.','2048 bits minimum, 4096 for higher security.');
q('rsa','medium','Giá trị e phổ biến nhất trong RSA?','Most common value of e in RSA?',['3','17','65537','257'],['3','17','65537','257'],2,'e = 65537 (2^16 + 1) phổ biến nhất.','e = 65537 (2^16 + 1) is most common.');
q('rsa','hard','Extended Euclidean Algorithm tính gì trong RSA?','Extended Euclidean Algorithm computes what in RSA?',['GCD','Modular inverse d','Số nguyên tố p','Hash'],['GCD','Modular inverse d','Prime p','Hash'],1,'Tính d = e^(-1) mod φ(n).','Computes d = e^(-1) mod φ(n).');
q('rsa','hard','RSA không phù hợp mã hoá dữ liệu lớn vì?','RSA not suitable for large data because?',['Không an toàn','Rất chậm so với mã hoá đối xứng','Không hỗ trợ UTF-8','Chỉ offline'],['Not secure','Very slow vs symmetric encryption','No UTF-8','Only offline'],1,'RSA chậm → dùng hybrid: RSA + AES.','RSA slow → use hybrid: RSA + AES.');
q('rsa','hard','OAEP trong RSA dùng để làm gì?','What is OAEP used for in RSA?',['Tăng tốc','Padding scheme ngăn tấn công chosen-ciphertext','Tạo khoá','Ký chữ ký'],['Speed up','Padding scheme to prevent chosen-ciphertext attacks','Generate keys','Sign signatures'],1,'OAEP: Optimal Asymmetric Encryption Padding.','OAEP: Optimal Asymmetric Encryption Padding.');

// ═══════════════════════════════════════════════════
// MERKLE (50 questions)
// ═══════════════════════════════════════════════════
q('merkle','easy','Cây Merkle là gì?','What is a Merkle Tree?',['Cây nhị phân lưu file','Cây hash: lá = hash(data), cha = hash(con)','Thuật toán sắp xếp','Đồ thị'],['Binary file tree','Hash tree: leaves = hash(data), parents = hash(children)','Sort algorithm','Graph'],1,'Merkle Tree: cấu trúc hash phân cấp.','Merkle Tree: hierarchical hash structure.');
q('merkle','easy','Merkle Root là gì?','What is Merkle Root?',['Hash đầu tiên','Hash gốc đại diện toàn bộ dữ liệu','Giao dịch đầu','Block header'],['First hash','Root hash representing all data','First transaction','Block header'],1,'Merkle Root = hash tổng hợp duy nhất.','Merkle Root = single summary hash.');
q('merkle','easy','Merkle Tree dùng để làm gì trong blockchain?','Merkle Tree purpose in blockchain?',['Mã hoá','Xác minh nhanh giao dịch tồn tại','Lưu hình ảnh','Kết nối P2P'],['Encrypt','Quickly verify transaction existence','Store images','P2P connect'],1,'Xác minh giao dịch trong O(log n).','Verify transactions in O(log n).');
q('merkle','easy','1 giao dịch thay đổi → Merkle Root?','1 transaction changes → Merkle Root?',['Không đổi','Thay đổi','Chỉ khi tx đầu','Tuỳ kích thước'],['No change','Changes','Only if first tx','Depends on size'],1,'Bất kỳ thay đổi nào → Root thay đổi.','Any change → Root changes.');
q('merkle','easy','Ai phát minh Merkle Tree?','Who invented Merkle Tree?',['Satoshi Nakamoto','Ralph Merkle','Vitalik Buterin','Alan Turing'],['Satoshi Nakamoto','Ralph Merkle','Vitalik Buterin','Alan Turing'],1,'Ralph Merkle phát minh năm 1979.','Ralph Merkle invented it in 1979.');
q('merkle','medium','Merkle Proof cần bao nhiêu hash cho N giao dịch?','Merkle Proof needs how many hashes for N txs?',['N','log₂(N)','N/2','1'],['N','log₂(N)','N/2','1'],1,'Chỉ cần log₂(N) hash.','Only log₂(N) hashes needed.');
q('merkle','medium','8 giao dịch → cây Merkle có mấy tầng?','8 transactions → how many Merkle Tree levels?',['2','3','4','8'],['2','3','4','8'],2,'8=2^3 → 3 tầng hash + 1 tầng lá = 4.','8=2^3 → 3 hash levels + 1 leaf = 4.');
q('merkle','medium','Số giao dịch lẻ → Merkle Tree xử lý sao?','Odd transaction count → Merkle Tree?',['Bỏ tx cuối','Nhân đôi tx cuối','Thêm tx rỗng','Lỗi'],['Drop last','Duplicate last','Add empty','Error'],1,'Node cuối được nhân đôi.','Last node is duplicated.');
q('merkle','medium','SPV dùng gì để xác minh giao dịch?','SPV uses what to verify transactions?',['Toàn bộ blockchain','Merkle Proof + Block header','Chỉ hash tx','Đào lại block'],['Entire blockchain','Merkle Proof + Block header','Only tx hash','Re-mine block'],1,'SPV: headers + Merkle Proof, không cần full blockchain.','SPV: headers + Merkle Proof, no full blockchain needed.');
q('merkle','medium','Merkle Patricia Trie dùng trong blockchain nào?','Merkle Patricia Trie is used in which blockchain?',['Bitcoin','Ethereum','Cardano','Solana'],['Bitcoin','Ethereum','Cardano','Solana'],1,'Ethereum dùng Modified Merkle Patricia Trie.','Ethereum uses Modified Merkle Patricia Trie.');
q('merkle','hard','Độ phức tạp xây dựng Merkle Tree từ N lá?','Complexity of building Merkle Tree from N leaves?',['O(N)','O(N log N)','O(N²)','O(log N)'],['O(N)','O(N log N)','O(N²)','O(log N)'],0,'O(N): mỗi node tính 1 hash, tổng ~2N nodes.','O(N): each node computes 1 hash, ~2N total nodes.');

// ═══════════════════════════════════════════════════
// BLOCKCHAIN BASICS (80 questions)
// ═══════════════════════════════════════════════════
q('blockchain_basics','easy','Blockchain là gì?','What is blockchain?',['Tiền tệ','Chuỗi khối liên kết bằng hash','Phần mềm ngân hàng','Mạng xã hội'],['Currency','Chain of blocks linked by hashes','Banking software','Social network'],1,'Blockchain: chuỗi blocks, mỗi block chứa hash block trước.','Blockchain: chain of blocks, each containing previous block hash.');
q('blockchain_basics','easy','Khối đầu tiên gọi là gì?','First block is called?',['Block Zero','Prime Block','Genesis Block','Origin Block'],['Block Zero','Prime Block','Genesis Block','Origin Block'],2,'Genesis Block: không có previous hash.','Genesis Block: no previous hash.');
q('blockchain_basics','easy','Blockchain tập trung hay phi tập trung?','Blockchain centralized or decentralized?',['Tập trung','Phi tập trung','Cả hai','Không liên quan'],['Centralized','Decentralized','Both','Not related'],1,'Phi tập trung: không server trung tâm.','Decentralized: no central server.');
q('blockchain_basics','easy','Mỗi block chứa gì?','What does each block contain?',['Chỉ giao dịch','Hash trước, data, timestamp, hash chính nó','Chỉ hash','Chỉ timestamp'],['Only transactions','Prev hash, data, timestamp, own hash','Only hash','Only timestamp'],1,'Block: prevHash, data, timestamp, nonce, hash.','Block: prevHash, data, timestamp, nonce, hash.');
q('blockchain_basics','easy','Tại sao blockchain bất biến?','Why is blockchain immutable?',['Không ai truy cập','Sửa 1 block phá vỡ chuỗi sau','Mật khẩu mạnh','Mã hoá'],['No access','Changing 1 block breaks chain after','Strong passwords','Encrypted'],1,'Sửa data → hash đổi → chuỗi bị phá.','Change data → hash changes → chain breaks.');
q('blockchain_basics','easy','Satoshi Nakamoto tạo ra?','Satoshi Nakamoto created?',['Ethereum','Bitcoin','Cardano','Ripple'],['Ethereum','Bitcoin','Cardano','Ripple'],1,'Satoshi: Bitcoin whitepaper 2008.','Satoshi: Bitcoin whitepaper 2008.');
q('blockchain_basics','easy','Bitcoin whitepaper năm?','Bitcoin whitepaper year?',['2005','2008','2010','2013'],['2005','2008','2010','2013'],1,'Tháng 10/2008.','October 2008.');
q('blockchain_basics','easy','Public blockchain khác private?','Public vs private blockchain?',['Public nhanh hơn','Public ai cũng tham gia, private cần quyền','Private an toàn hơn','Không khác'],['Public faster','Public open to all, private needs permission','Private more secure','No difference'],1,'Public: mở. Private: cần permission.','Public: open. Private: needs permission.');
q('blockchain_basics','easy','Ledger là gì?','What is a ledger?',['Phần mềm đào','Sổ cái giao dịch','Loại coin','Thuật toán'],['Mining software','Transaction record book','Coin type','Algorithm'],1,'Ledger: bản ghi tất cả giao dịch.','Ledger: record of all transactions.');
q('blockchain_basics','easy','Token khác coin thế nào?','Token vs coin?',['Giống nhau','Coin có blockchain riêng, token chạy trên chain khác','Token đắt hơn','Coin chỉ thanh toán'],['Same','Coin has own chain, token runs on another','Token more expensive','Coin only for payments'],1,'Coin (BTC, ETH): chain riêng. Token: trên chain khác.','Coin: own chain. Token: on another chain.');
q('blockchain_basics','easy','Ví blockchain lưu gì?','What does a blockchain wallet store?',['Tiền thật','Private key và public key','Toàn bộ blockchain','File cá nhân'],['Real money','Private and public keys','Entire blockchain','Personal files'],1,'Ví lưu khoá, coin nằm trên blockchain.','Wallet stores keys, coins are on blockchain.');
q('blockchain_basics','easy','Giao dịch blockchain gồm gì?','Blockchain transaction includes?',['Chỉ số tiền','Sender, receiver, amount, chữ ký số','Chỉ địa chỉ','Chỉ hash'],['Only amount','Sender, receiver, amount, digital signature','Only address','Only hash'],1,'Giao dịch: sender, receiver, amount, signature, timestamp.','Transaction: sender, receiver, amount, signature, timestamp.');
q('blockchain_basics','medium','Consensus mechanism dùng để?','Consensus mechanism used for?',['Mã hoá','Đảm bảo tất cả node đồng ý về trạng thái','Tạo ví','Tăng tốc'],['Encrypt','Ensure all nodes agree on state','Create wallets','Speed up'],1,'Consensus: tất cả node đồng ý về blockchain state.','Consensus: all nodes agree on blockchain state.');
q('blockchain_basics','medium','PoS khác PoW thế nào?','How does PoS differ from PoW?',['PoS nhanh hơn','PoS dùng coin stake, PoW dùng sức tính toán','PoS kém an toàn','Không khác'],['PoS faster','PoS uses staked coins, PoW uses computing power','PoS less secure','No difference'],1,'PoS: stake coins. PoW: computing power.','PoS: stake coins. PoW: computing power.');
q('blockchain_basics','medium','51% attack là gì?','What is 51% attack?',['51% node offline','Entity kiểm soát >50% hash rate','51% tx bị từ chối','51% coin mất'],['51% nodes offline','Entity controls >50% hash rate','51% tx rejected','51% coins lost'],1,'51% attack: kiểm soát >50% mạng → double-spend.','51% attack: control >50% network → double-spend.');
q('blockchain_basics','medium','Fork là gì?','What is a fork?',['Lỗi','Phân nhánh blockchain thành 2','Cập nhật','Loại giao dịch'],['Error','Blockchain splits into 2','Update','Transaction type'],1,'Fork: blockchain tách thành 2 nhánh.','Fork: blockchain splits into 2 branches.');
q('blockchain_basics','medium','Hard fork vs soft fork?','Hard fork vs soft fork?',['Hard nhanh hơn','Hard không tương thích ngược, soft tương thích','Soft an toàn hơn','Không khác'],['Hard faster','Hard not backward-compatible, soft is','Soft more secure','No difference'],1,'Hard fork: chain riêng. Soft fork: tương thích ngược.','Hard fork: separate chain. Soft fork: backward-compatible.');
q('blockchain_basics','medium','Double spending là gì?','What is double spending?',['Chi gấp đôi','Dùng cùng coin cho 2 giao dịch','Trả phí 2 lần','Đào 2 block cùng lúc'],['Spending double','Using same coin for 2 transactions','Paying fee twice','Mining 2 blocks'],1,'Double spending: chi tiêu cùng coin 2 lần.','Double spending: spending same coin twice.');
q('blockchain_basics','medium','Blockchain giải quyết double spending bằng?','How blockchain solves double spending?',['Mật khẩu','Consensus + distributed ledger','AI','Biometric'],['Passwords','Consensus + distributed ledger','AI','Biometrics'],1,'Consensus + sổ cái phân tán.','Consensus + distributed ledger.');
q('blockchain_basics','medium','UTXO model là gì?','What is UTXO model?',['Mô hình số dư','Unspent Transaction Output model','Mô hình token','Mô hình smart contract'],['Balance model','Unspent Transaction Output model','Token model','Smart contract model'],1,'UTXO: mỗi output chưa tiêu là input tiềm năng.','UTXO: each unspent output is a potential input.');
q('blockchain_basics','hard','BFT giải quyết vấn đề gì?','What does BFT solve?',['Tốc độ','Node gian lận/lỗi trong hệ thống phân tán','Kích thước data','Mã hoá yếu'],['Speed','Fraudulent/faulty nodes in distributed systems','Data size','Weak encryption'],1,'BFT: hệ thống hoạt động đúng dù có node lỗi.','BFT: system works correctly despite faulty nodes.');
q('blockchain_basics','hard','CAP theorem nói gì?','What does CAP theorem say?',['Về giá coin','Không thể đạt C, A, P đồng thời','Về tốc độ tx','Về chi phí đào'],['About price','Cannot achieve C, A, P simultaneously','About tx speed','About mining cost'],1,'CAP: Consistency, Availability, Partition tolerance — chỉ được 2/3.','CAP: only 2 of 3 can be achieved.');
q('blockchain_basics','hard','Finality trong blockchain nghĩa là gì?','What does finality mean in blockchain?',['Kết thúc mining','Giao dịch không thể bị đảo ngược sau khi xác nhận','Block cuối cùng','Chain kết thúc'],['End of mining','Transaction cannot be reversed once confirmed','Last block','Chain ends'],1,'Finality: giao dịch xác nhận xong = không thể đảo.','Finality: once confirmed, transaction is irreversible.');

// ═══════════════════════════════════════════════════
// CRYPTO FUNDAMENTALS (50 questions)
// ═══════════════════════════════════════════════════
q('crypto_fundamentals','easy','Mã hoá đối xứng dùng bao nhiêu khoá?','Symmetric encryption uses how many keys?',['1','2','3','0'],['1','2','3','0'],0,'1 khoá cho cả mã hoá và giải mã.','1 key for both encrypt and decrypt.');
q('crypto_fundamentals','easy','AES là loại mã hoá nào?','What type is AES?',['Bất đối xứng','Đối xứng','Hàm băm','Chữ ký số'],['Asymmetric','Symmetric','Hash','Digital signature'],1,'AES: Advanced Encryption Standard, đối xứng.','AES: Advanced Encryption Standard, symmetric.');
q('crypto_fundamentals','easy','Cryptography là gì?','What is cryptography?',['Lập trình web','Khoa học bảo mật thông tin','Khoa học tiền tệ','Khoa học máy tính'],['Web programming','Science of securing information','Money science','Computer science'],1,'Mật mã học: kỹ thuật bảo mật thông tin.','Cryptography: techniques for securing info.');
q('crypto_fundamentals','easy','Plaintext là gì?','What is plaintext?',['Đã mã hoá','Dữ liệu gốc chưa mã hoá','Khoá','Chữ ký'],['Encrypted','Original unencrypted data','Key','Signature'],1,'Plaintext: dữ liệu gốc.','Plaintext: original data.');
q('crypto_fundamentals','easy','Ciphertext là gì?','What is ciphertext?',['Dữ liệu gốc','Dữ liệu đã mã hoá','Hash','Public key'],['Original data','Encrypted data','Hash','Public key'],1,'Ciphertext: kết quả mã hoá.','Ciphertext: encryption result.');
q('crypto_fundamentals','easy','XOR là phép toán gì?','What is XOR?',['Cộng','Exclusive OR','Nhân','Chia'],['Addition','Exclusive OR','Multiplication','Division'],1,'XOR: 0⊕0=0, 0⊕1=1, 1⊕0=1, 1⊕1=0.','XOR: 0⊕0=0, 0⊕1=1, 1⊕0=1, 1⊕1=0.');
q('crypto_fundamentals','easy','Encryption là gì?','What is encryption?',['Giải mã','Chuyển plaintext thành ciphertext','Tạo hash','Ký chữ ký'],['Decryption','Converting plaintext to ciphertext','Creating hash','Signing'],1,'Encryption: biến dữ liệu thành dạng không đọc được.','Encryption: making data unreadable.');
q('crypto_fundamentals','easy','Decryption là gì?','What is decryption?',['Mã hoá','Chuyển ciphertext về plaintext','Tạo hash','Mining'],['Encryption','Converting ciphertext back to plaintext','Hashing','Mining'],1,'Decryption: khôi phục dữ liệu gốc từ ciphertext.','Decryption: recovering original data from ciphertext.');
q('crypto_fundamentals','medium','Diffie-Hellman dùng để?','Diffie-Hellman used for?',['Mã hoá file','Trao đổi khoá qua kênh không an toàn','Ký chữ ký','Tạo hash'],['Encrypt files','Key exchange over insecure channel','Sign signatures','Create hashes'],1,'DH: tạo shared secret qua kênh công khai.','DH: create shared secret over public channel.');
q('crypto_fundamentals','medium','ECC có ưu điểm gì so với RSA?','ECC advantage over RSA?',['Dễ hiểu','Cùng bảo mật với khoá ngắn hơn','Nhanh gấp đôi','Miễn phí'],['Easier','Same security with shorter keys','Twice faster','Free'],1,'ECC 256-bit ≈ RSA 3072-bit.','ECC 256-bit ≈ RSA 3072-bit.');
q('crypto_fundamentals','medium','Nonce trong mật mã là gì?','What is a nonce in cryptography?',['Mật khẩu','Số dùng 1 lần ngăn replay attack','Public key','Chữ ký'],['Password','Number used once to prevent replay','Public key','Signature'],1,'Nonce = Number used ONCE.','Nonce = Number used ONCE.');
q('crypto_fundamentals','medium','Digital Certificate chứa gì?','Digital Certificate contains?',['Chỉ public key','Public key, identity, chữ ký CA','Chỉ tên','Private key'],['Only public key','Public key, identity, CA signature','Only name','Private key'],1,'Certificate: public key + identity + CA signature.','Certificate: public key + identity + CA signature.');
q('crypto_fundamentals','medium','PKI là gì?','What is PKI?',['Loại coin','Public Key Infrastructure - hạ tầng quản lý khoá công khai','Phần mềm đào','Giao thức mạng'],['Coin type','Public Key Infrastructure','Mining software','Network protocol'],1,'PKI: hệ thống quản lý chứng chỉ số và khoá công khai.','PKI: system managing digital certificates and public keys.');
q('crypto_fundamentals','hard','Zero-knowledge proof là gì?','What is a zero-knowledge proof?',['Chứng minh không có kiến thức','Chứng minh biết thông tin mà không tiết lộ nó','Chứng minh hash = 0','Không cần chứng minh'],['Proving no knowledge','Proving knowledge without revealing it','Proving hash = 0','No proof needed'],1,'ZKP: chứng minh biết bí mật mà không tiết lộ bí mật đó.','ZKP: prove knowledge of secret without revealing it.');

// ═══════════════════════════════════════════════════
// NETWORK (40 questions)
// ═══════════════════════════════════════════════════
q('network','easy','P2P network là gì?','What is P2P network?',['Có server trung tâm','Mạng ngang hàng, mỗi node là client+server','Chỉ 2 máy','Mạng xã hội'],['Central server','Peer network, each node is client+server','Only 2 machines','Social network'],1,'P2P: mỗi node bình đẳng.','P2P: each node is equal.');
q('network','easy','Node trong blockchain là gì?','What is a blockchain node?',['Loại coin','Máy tính tham gia mạng blockchain','Giao dịch','Block'],['Coin type','Computer in blockchain network','Transaction','Block'],1,'Node: máy tính chạy phần mềm blockchain.','Node: computer running blockchain software.');
q('network','easy','Full node khác light node?','Full node vs light node?',['Full nhanh hơn','Full lưu toàn bộ, light chỉ headers','Light an toàn hơn','Không khác'],['Full faster','Full stores all, light only headers','Light more secure','No difference'],1,'Full: toàn bộ blockchain. Light: chỉ headers.','Full: entire blockchain. Light: headers only.');
q('network','easy','Broadcast là gì?','What is broadcast?',['Gửi 1 node','Gửi đến tất cả node','Xoá tx','Mã hoá'],['Send to 1','Send to all nodes','Delete tx','Encrypt'],1,'Broadcast: gửi thông tin tới toàn mạng.','Broadcast: send info to entire network.');
q('network','easy','Testnet là gì?','What is a testnet?',['Mạng chính','Mạng thử nghiệm với coin giả','Mạng private','VPN'],['Main network','Test network with fake coins','Private network','VPN'],1,'Testnet: mạng test, coin không có giá trị thật.','Testnet: test network, coins have no real value.');
q('network','medium','Gossip protocol hoạt động sao?','How does gossip protocol work?',['Gửi cho tất cả','Mỗi node gửi vài láng giềng → lan truyền','Chỉ full nodes','Server trung tâm'],['Send to all','Each node tells few neighbors → spreads','Only full nodes','Central server'],1,'Gossip: node → vài peer → lan rộng.','Gossip: node → few peers → propagates.');
q('network','medium','Orphan block là gì?','What is an orphan block?',['Block lỗi','Block hợp lệ nhưng không trên chain chính','Block đầu','Block trống'],['Error block','Valid block not on main chain','First block','Empty block'],1,'Orphan: block bị bỏ vì block cạnh tranh được chọn.','Orphan: block discarded because competing block was chosen.');
q('network','medium','Propagation delay ảnh hưởng gì?','What does propagation delay affect?',['Giá coin','Thời gian giao dịch/block lan truyền qua mạng','Kích thước blockchain','Số coin'],['Coin price','Time for tx/block to propagate across network','Blockchain size','Coin count'],1,'Delay cao → tăng xác suất fork tạm thời.','High delay → more temporary forks.');

// ═══════════════════════════════════════════════════
// SMART CONTRACTS (30 questions)
// ═══════════════════════════════════════════════════
q('smart_contracts','easy','Smart contract là gì?','What is a smart contract?',['Hợp đồng giấy','Code tự thực thi trên blockchain','Tiền mã hoá','Phần mềm ví'],['Paper contract','Self-executing code on blockchain','Cryptocurrency','Wallet software'],1,'Smart contract: code tự động trên blockchain.','Smart contract: auto-executing code on blockchain.');
q('smart_contracts','easy','Blockchain nào đầu tiên hỗ trợ smart contract?','First blockchain with smart contracts?',['Bitcoin','Ethereum','Solana','Cardano'],['Bitcoin','Ethereum','Solana','Cardano'],1,'Ethereum (2015) bởi Vitalik Buterin.','Ethereum (2015) by Vitalik Buterin.');
q('smart_contracts','easy','Gas trong Ethereum là gì?','What is gas in Ethereum?',['Nhiên liệu','Đơn vị phí tính toán','Loại token','Tên ví'],['Fuel','Computational fee unit','Token type','Wallet name'],1,'Gas = đơn vị đo phí tính toán.','Gas = computational fee unit.');
q('smart_contracts','easy','EVM là gì?','What is EVM?',['Loại coin','Ethereum Virtual Machine','Email','Exchange'],['Coin type','Ethereum Virtual Machine','Email','Exchange'],1,'EVM: môi trường chạy smart contract trên Ethereum.','EVM: environment for running smart contracts on Ethereum.');
q('smart_contracts','easy','DApp là gì?','What is a DApp?',['App mobile','Ứng dụng phi tập trung trên blockchain','App desktop','App ngân hàng'],['Mobile app','Decentralized application on blockchain','Desktop app','Banking app'],1,'DApp: backend = smart contract, frontend = web.','DApp: backend = smart contract, frontend = web.');
q('smart_contracts','medium','Solidity là gì?','What is Solidity?',['Hệ điều hành','Ngôn ngữ smart contract cho Ethereum','Framework frontend','Database'],['OS','Smart contract language for Ethereum','Frontend framework','Database'],1,'Solidity: ngôn ngữ lập trình cho EVM.','Solidity: programming language for EVM.');
q('smart_contracts','medium','Reentrancy attack là gì?','What is a reentrancy attack?',['Tấn công mạng','Smart contract bị gọi lại đệ quy trước khi state cập nhật','Tấn công vật lý','Brute force'],['Network attack','Contract recursively called before state updates','Physical attack','Brute force'],1,'Reentrancy: contract gọi lại trước khi cập nhật balance.','Reentrancy: contract called back before balance updates.');
q('smart_contracts','medium','Oracle trong blockchain là gì?','What is an oracle in blockchain?',['Công ty','Dịch vụ cung cấp dữ liệu bên ngoài cho smart contract','Database','Loại node'],['Company','Service providing external data to smart contracts','Database','Node type'],1,'Oracle: cầu nối dữ liệu thế giới thực → blockchain.','Oracle: bridge real-world data → blockchain.');

// ═══════════════════════════════════════════════════
// SECURITY (20 questions)
// ═══════════════════════════════════════════════════
q('security','easy','Phishing trong crypto là gì?','What is phishing in crypto?',['Tấn công mã hoá','Lừa tiết lộ private key/seed phrase','51% attack','Smart contract exploit'],['Encryption attack','Tricking users to reveal keys/seed','51% attack','Smart contract exploit'],1,'Phishing: giả mạo để lừa lấy khoá.','Phishing: fake sites to steal keys.');
q('security','easy','Seed phrase dùng để?','Seed phrase used for?',['Đăng nhập email','Khôi phục ví crypto','Mã hoá file','Kết nối internet'],['Log into email','Recover crypto wallet','Encrypt files','Connect internet'],1,'Seed phrase (12-24 từ): khôi phục ví.','Seed phrase (12-24 words): recover wallet.');
q('security','easy','Cold wallet là gì?','What is a cold wallet?',['Ví online','Ví offline không kết nối internet','Ví miễn phí','Ví ngân hàng'],['Online wallet','Offline wallet not connected to internet','Free wallet','Bank wallet'],1,'Cold wallet: không online → an toàn hơn.','Cold wallet: not online → more secure.');
q('security','easy','Hot wallet là gì?','What is a hot wallet?',['Ví offline','Ví kết nối internet','Ví phần cứng','Ví giấy'],['Offline wallet','Wallet connected to internet','Hardware wallet','Paper wallet'],1,'Hot wallet: online, tiện nhưng rủi ro hơn.','Hot wallet: online, convenient but riskier.');
q('security','easy','2FA là gì?','What is 2FA?',['Loại coin','Xác thực 2 yếu tố','Thuật toán hash','Giao thức mạng'],['Coin type','Two-factor authentication','Hash algorithm','Network protocol'],1,'2FA: cần 2 bằng chứng xác thực (mật khẩu + OTP).','2FA: requires 2 authentication proofs (password + OTP).');
q('security','medium','Sybil attack là gì?','What is a Sybil attack?',['Tấn công vật lý','Tạo nhiều node giả để thao túng mạng','Tấn công mã hoá','Phishing'],['Physical attack','Creating fake nodes to manipulate network','Encryption attack','Phishing'],1,'Sybil: tạo nhiều identity giả chiếm đa số mạng.','Sybil: creating fake identities to dominate network.');
q('security','medium','Replay attack là gì?','What is a replay attack?',['Xem lại video','Phát lại giao dịch hợp lệ trên chain khác','Đào lại block','Hack camera'],['Watching replay','Replaying valid tx on another chain','Re-mining block','Camera hack'],1,'Replay: dùng tx chain A trên chain B (sau fork).','Replay: using chain A tx on chain B (after fork).');
q('security','medium','Multi-signature wallet là gì?','What is multi-sig wallet?',['Ví 1 chữ ký','Ví cần nhiều chữ ký để thực hiện giao dịch','Ví miễn phí','Ví exchange'],['Single-sig wallet','Wallet needing multiple signatures for tx','Free wallet','Exchange wallet'],1,'Multi-sig: cần M/N chữ ký (VD: 2/3) để gửi tx.','Multi-sig: needs M/N signatures (e.g. 2/3) to send tx.');

// Additional 358 real questions were generated by fix_q.js → fix_q5.js
// and are already present in quiz_questions.json (total 500 questions).

console.log(`Total questions: ${questions.length}`);
const stats = {};
for (const q of questions) {
  if (!stats[q.topic]) stats[q.topic] = {easy:0,medium:0,hard:0};
  stats[q.topic][q.difficulty]++;
}
console.table(stats);

const outPath = path.join(__dirname, 'src', 'data', 'quiz_questions.json');
fs.writeFileSync(outPath, JSON.stringify(questions, null, 2), 'utf8');
console.log(`Written to ${outPath}`);
